Bundle-Name = dbUnit Dataset Editor
Bundle-Vendor = dbUnit
editor.name = dbUnit Dataset Editor
context.tablesPage.name = dbUnit Dataset Tables Page
context.tablesPage.description = Active while the Tables page of the dbUnit Dataset Editor is showing.
command.category.name = dbUnit Dataset
command.insertRowAbove.name = Insert Row Above
command.insertRowBelow.name = Insert Row Below
command.deleteRows.name = Delete Rows
command.duplicateRows.name = Duplicate Rows
command.moveRowsUp.name = Move Rows Up
command.moveRowsDown.name = Move Rows Down
command.addColumn.name = Add Column...
command.renameColumn.name = Rename Column...
command.deleteColumn.name = Delete Column
command.addTable.name = Add Table...
command.renameTable.name = Rename Table...
command.deleteTable.name = Delete Table
command.setNull.name = Set to NULL
command.setEmptyString.name = Set to Empty String
command.fillDown.name = Fill Down
command.editCellInDialog.name = Edit Cell in Dialog...
